// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function str(prim) {
  return prim;
}

function renderForm(time, setTime, numbers, setNumbers, caption1, setCaption1, caption2, setCaption2) {
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "text-2xl font-semibold"
                }, "Image Generator"), React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("label", {
                      className: "block mb-2",
                      htmlFor: "caption1"
                    }, "Location"), React.createElement("input", {
                      className: "appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "caption1",
                      placeholder: "waynadu melppadi",
                      value: caption1,
                      onChange: (function ($$event) {
                          return Curry._1(setCaption1, $$event.target.value);
                        })
                    })), React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("label", {
                      className: "block mb-2",
                      htmlFor: "caption1"
                    }, "Requirment"), React.createElement("input", {
                      className: "appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "caption2",
                      placeholder: "Food for 100 people",
                      value: caption2,
                      onChange: (function ($$event) {
                          return Curry._1(setCaption2, $$event.target.value);
                        })
                    })), React.createElement("div", undefined, React.createElement("label", {
                      className: "block mb-2",
                      htmlFor: "time"
                    }, "Message recieved at"), React.createElement("input", {
                      className: "appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "time",
                      placeholder: "Friday 4 PM ",
                      value: time,
                      onChange: (function ($$event) {
                          return Curry._1(setTime, $$event.target.value);
                        })
                    })), React.createElement("div", {
                  className: "w-full mt-4"
                }, React.createElement("label", {
                      className: "block mb-2",
                      htmlFor: "numbers"
                    }, "number"), React.createElement("input", {
                      className: "appearance-none h-10 mt-1 block w-full text-gray-800 border border-gray-400 rounded py-2 px-4 text-sm bg-gray-100 hover:bg-gray-200 focus:outline-none focus:bg-white focus:border-primary-400",
                      id: "numbers",
                      placeholder: "0000000000,000000000",
                      value: numbers,
                      onChange: (function ($$event) {
                          return Curry._1(setNumbers, $$event.target.value);
                        })
                    })));
}

function renderView(caption1, caption2, time, numbers) {
  return React.createElement("div", {
              className: "w-full"
            }, React.createElement("div", {
                  className: "text-2xl font-semibold"
                }, "Image"), React.createElement("div", {
                  className: "text-2xl font-semibold"
                }, caption1), React.createElement("div", {
                  className: "text-4xl font-bold"
                }, caption2), React.createElement("div", {
                  className: "text-md"
                }, "Message recieved at " + time), React.createElement("div", {
                  className: "text-md"
                }, "Call for more info"), React.createElement("div", {
                  className: "text-3xl"
                }, numbers), React.createElement("div", {
                  className: "text-3xl"
                }, "footer"));
}

function Component1(Props) {
  var match = React.useState((function () {
          return true;
        }));
  var setShowForm = match[1];
  var match$1 = React.useState((function () {
          return "";
        }));
  var caption1 = match$1[0];
  var match$2 = React.useState((function () {
          return "";
        }));
  var caption2 = match$2[0];
  var match$3 = React.useState((function () {
          return "";
        }));
  var time = match$3[0];
  var match$4 = React.useState((function () {
          return "";
        }));
  var numbers = match$4[0];
  return React.createElement("div", {
              className: "h-screen flex flex-col justify-center items-center flex-wrap bg-white"
            }, React.createElement("div", {
                  className: "max-w-xl w-full rounded overflow-hidden shadow-lg px-20 py-10"
                }, match[0] ? React.createElement("div", undefined, renderForm(time, match$3[1], numbers, match$4[1], caption1, match$1[1], caption2, match$2[1])) : React.createElement("div", undefined, renderView(caption1, caption2, time, numbers))), React.createElement("div", {
                  className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4",
                  onClick: (function (param) {
                      return Curry._1(setShowForm, (function (form) {
                                    return !form;
                                  }));
                    })
                }, "Generate Image"));
}

var make = Component1;

exports.str = str;
exports.renderForm = renderForm;
exports.renderView = renderView;
exports.make = make;
/* react Not a pure module */
