// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Component1$ReactHooksTemplate = require("./Component1.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Component1$ReactHooksTemplate.make, { }), "index1");

/*  Not a pure module */
