// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ScreenshotJs = require("./screenshot.js");

function str(prim) {
  return prim;
}

function htmlToImage(prim) {
  ScreenshotJs.default(prim);
  return /* () */0;
}

function Screenshot(Props) {
  var elementId = Props.elementId;
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "text-center"
                }, React.createElement("button", {
                      className: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-4 ml-4",
                      onClick: (function (param) {
                          ScreenshotJs.default(elementId);
                          return /* () */0;
                        })
                    }, "Download Image")));
}

var make = Screenshot;

exports.str = str;
exports.htmlToImage = htmlToImage;
exports.make = make;
/* react Not a pure module */
